CREATE DATABASE QL_SANBONG
USE QL_SANBONG

CREATE TABLE LOAISAN
(
	MALOAI NCHAR(50),
	TENLOAI NVARCHAR(50),
	CONSTRAINT PK_LOAISAN PRIMARY KEY (MALOAI)
)

CREATE TABLE SANBONG
(
	MASAN NCHAR(50) NOT NULL,
	TENSAN NVARCHAR(50),
	GIATHUE INT, 
	MALOAI NCHAR(50)
	CONSTRAINT PK_SANBONG PRIMARY KEY (MASAN),
	CONSTRAINT FK_SANBONH FOREIGN KEY (MALOAI) REFERENCES LOAISAN(MALOAI)
)

CREATE TABLE KHACHHANG
(
	MAKH NCHAR(50) NOT NULL,
	TENKH NVARCHAR(50),
	DIACHI NVARCHAR(50),
	SODIENTHOAI NCHAR(10),
	CONSTRAINT PK_KHAHCHHANG PRIMARY KEY(MAKH),
	
)

CREATE TABLE LICHDATSAN
(
	MALICH NCHAR(50) NOT NULL,
	NGAYDAT DATE,
	GIOBATDAU TIME,
	GIOKETTHUC TIME,
	MAKH NCHAR(50),
	MASAN NCHAR(50),
	CONSTRAINT PK_LICHDATSAN PRIMARY KEY(MALICH),
	CONSTRAINT FK_LICHDATSANMSAN FOREIGN KEY (MASAN) REFERENCES SANBONG(MASAN),
	CONSTRAINT FK_LICHDATSANKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
)

CREATE TABLE HOADON
(
	MAHD NCHAR(50) NOT NULL,
	NGAYTAO DATE,
	TONGTIEN INT,
	TRANGTHAI NVARCHAR(50),
	MALICH NCHAR(50),
	MAKH NCHAR(50),
	CONSTRAINT PK_HOADON PRIMARY KEY (MAHD),
	CONSTRAINT FK_LICHHOADON FOREIGN KEY (MALICH) REFERENCES LICHDATSAN(MALICH),
	CONSTRAINT FK_HOADONKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
)

CREATE TABLE DICHVU
(
	MADV NCHAR(50) NOT NULL,
	TENDV NVARCHAR(50),
	DONGIA INT
	CONSTRAINT PK_DICHVU PRIMARY KEY (MADV),
)

CREATE TABLE CHITIETHOADON
(
	MADV NCHAR(50) NOT NULL,
	MAHD NCHAR (50) NOT NULL,
	SOLUONG INT,
	CONSTRAINT PK_CHITIETHOADON PRIMARY KEY (MADV,MAHD),
	CONSTRAINT FK_CHITIETHOADON FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
	CONSTRAINT FK_CHITIETHOADONDV FOREIGN KEY(MADV) REFERENCES DICHVU(MADV)
)

CREATE TABLE NHANVIEN
(
	MANHANVIEN VARCHAR(50) NOT NULL,
	TENNHANVIEN NVARCHAR(50),
	TAIKHOAN VARCHAR(50) NOT NULL,
	MATKHAU VARCHAR(50),
	EMAIL NVARCHAR(50),
	SDT CHAR(10),
)


-- Ràng buộc tài khoản không được trùng lặp
ALTER TABLE NHANVIEN
ADD CONSTRAINT UQ_TAIKHOAN UNIQUE (TAIKHOAN);

-- Ràng buộc mật khẩu có độ dài tối thiểu là 10 ký tự
ALTER TABLE NHANVIEN
ADD CONSTRAINT CK_MATKHAU_LENGTH CHECK (LEN(MATKHAU) >= 10);

ALTER TABLE NHANVIEN
ADD CONSTRAINT CK_EMAIL_FORMAT CHECK (EMAIL LIKE '%@%.%');

ALTER TABLE NHANVIEN
ADD CONSTRAINT CK_SDT_FORMAT CHECK (SDT LIKE '[0-9]%')


INSERT INTO LOAISAN(MALOAI, TENLOAI)
VALUES
('ML01',N'SÂN 5'),
('ML02',N'SÂN 7'),
('ML03',N'SÂN 11')

INSERT INTO DICHVU
VALUES
('DV01',N'Trà sữa',20000),
('DV02',N'Nước Ngọt',10000),
('DV03',N'Cá Viên',10000)

INSERT INTO SANBONG(MASAN, TENSAN, GIATHUE, MALOAI)
values
('MS001','SÂN 1',50000,'ML01'),
('MS002','SÂN 2',50000,'ML01'),
('MS003','SÂN 3',50000,'ML01'),
('MS004','SÂN 4',70000,'ML02'),
('MS005','SÂN 5',70000,'ML02'),
('MS006','SÂN 6',70000,'ML02')

INSERT INTO NHANVIEN
VALUES('NV01',N'Võ Khánh Hưng','khanhhung2003','hung199535hcm','vokhanhhung03@gmail.com','0763270903')